#!/usr/bin/env php
<?php

require dirname(__DIR__) . '/vendor/autoload.php';

use Kirby\Cms\App as Kirby;
use Kirby\Toolkit\F;

$base = dirname(__DIR__);
$kirby = new Kirby([
    'roots' => [
        'index'    => $base . '/public',
        'base'     => $base,
        'site'     => $base . '/site',
        'storage'  => $storage = $base . '/storage',
        'content'  => $storage . '/content',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'sessions' => $storage . '/sessions',
    ]
]);

$outputFolder = $base . '/static';

// Render and save html files
$staticSiteGenerator = new D4L\StaticSiteGenerator($kirby, $pathsToCopy = null, $pages = null);
$fileList = $staticSiteGenerator->generate($outputFolder, $baseUrl = '/', $preserve = []);

// Generate sitemap
$mapper = option('cre8ivclick.sitemapper.customMap');
$sitemapXml = snippet('sitemapper/xml', ['map' => $mapper(site())], true);
$sitemapXsl = snippet('sitemapper/xsl', [], true);
F::write($outputFolder . '/sitemap.xml', $sitemapXml);
F::write($outputFolder . '/sitemap.xsl', $sitemapXsl);

echo 'Static site successfully built to ' . $outputFolder;
