#!/usr/bin/env php
<?php

$base = dirname(__DIR__);
require $base . '/vendor/autoload.php';

$kirby = new Kirby\Cms\App([
    'roots' => [
        'index'    => $base . '/public',
        'base'     => $base,
        'site'     => $base . '/site',
        'storage'  => $storage = $base . '/storage',
        'content'  => $storage . '/content',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'logs'     => $storage . '/logs',
        'sessions' => $storage . '/sessions',
    ]
]);

$outputFolder = $base . '/static';

// Render and save html files
$staticSiteGenerator = new D4L\StaticSiteGenerator($kirby, $pathsToCopy = null, $pages = null);
$fileList = $staticSiteGenerator->generate($outputFolder, $baseUrl = '/', $preserve = []);

echo 'Static site successfully built to ' . $outputFolder . PHP_EOL;
