#!/usr/bin/env php
<?php

// Check if we are indeed on the command line
if (php_sapi_name() !== 'cli') die();

$base = dirname(__DIR__);
require $base . '/vendor/autoload.php';

$kirby = new Kirby\Cms\App([
    'roots' => [
        'index'    => $base . '/public',
        'base'     => $base,
        'site'     => $base . '/site',
        'storage'  => $storage = $base . '/storage',
        'content'  => $storage . '/content',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'logs'     => $storage . '/logs',
        'sessions' => $storage . '/sessions',
    ]
]);

echo "\033[1mGenerating static pages and media…\033[0m\n";

$outputFolder = $base . '/static';
$staticSiteGenerator = new D4L\StaticSite\Generator($kirby);
$fileList = $staticSiteGenerator->generate($outputFolder);

echo "\033[32mSuccessfully built static site to {$outputFolder}.\033[0m\n";
